name: Build

on: [push, workflow_dispatch, pull_request]

env:
  XMAKE_ROOT: y

permissions:
  contents: write

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      fullSemVer: ${{ steps.version_step.outputs.fullSemVer }}
      semVer: ${{ steps.version_step.outputs.semVer }}
      informationalVersion: ${{ steps.version_step.outputs.informationalVersion }}
      preReleaseLabel: ${{ steps.version_step.outputs.preReleaseLabel }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Fetch all tags
      run: |
        git fetch --tags --force
        git tag
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v3.2.1
      with:
        versionSpec: '5.12.x'
    - name: Determine Version
      id: version_step
      uses: gittools/actions/gitversion/execute@v3.2.1

  windows_build:
    needs: versioning
    runs-on: windows-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        actions-cache-folder: '.xmake-cache'
        actions-cache-key: xmake-${{ runner.os }}
    - name: Build
      run: |
        xmake build -y
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: s2dumper_windows
        path: build/windows/x64/release/s2dumper.exe
    - name: Upload PDB as artifact
      uses: actions/upload-artifact@v4
      with:
        name: s2dumper_windows_pdb
        path: build/windows/x64/release/s2dumper.pdb

  linux_build:
    needs: versioning
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt install -y libreadline-dev
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        actions-cache-folder: '.xmake-cache'
        actions-cache-key: xmake-${{ runner.os }}
    - name: Build
      run: |
        xmake f --cc=gcc-14 --cxx=g++-14 -y
        xmake build -y
    - name: Upload binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: s2dumper_linux
        path: build/linux/x86_64/release/s2dumper

  packaging:
    needs: [versioning, windows_build, linux_build]
    runs-on: ubuntu-latest
    env:
      WINDOWS_FOLDER: s2dumper-windows-v${{ needs.versioning.outputs.semVer }}
      LINUX_FOLDER: s2dumper-linux-v${{ needs.versioning.outputs.semVer }}
      PDB_FOLDER: s2dumper-windows-v${{ needs.versioning.outputs.semVer }}-pdb
    steps:
    - name: Download windows artifact
      uses: actions/download-artifact@v4
      with:
        name: s2dumper_windows
        path: ./${{ env.WINDOWS_FOLDER }}
    - name: Download windows pdb artifact
      uses: actions/download-artifact@v4
      with:
        name: s2dumper_windows_pdb
        path: ./${{ env.PDB_FOLDER }}
    - name: Download linux artifact
      uses: actions/download-artifact@v4
      with:
        name: s2dumper_linux
        path: ./${{ env.LINUX_FOLDER }}

    - name: Create packages
      run: |
        chmod +x ${{ env.LINUX_FOLDER }}/s2dumper

        mkdir -p release
        zip -j "release/${{ env.WINDOWS_FOLDER }}.zip" "${{ env.WINDOWS_FOLDER }}"/*
        zip -j "release/${{ env.LINUX_FOLDER }}.zip" "${{ env.LINUX_FOLDER }}"/*
        zip -j "release/${{ env.PDB_FOLDER }}.zip" "${{ env.PDB_FOLDER }}"/*
        ls -la release

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: s2dumper-package-${{ needs.versioning.outputs.semVer }}
        path: release/*.zip

  releasing:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: [versioning, packaging]
    runs-on: ubuntu-latest
    env:
      TAG_NAME: v${{ needs.versioning.outputs.semVer }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create tag
      run: |
        TAG_NAME="${{ env.TAG_NAME }}"
        MSG="Release v${{ needs.versioning.outputs.semVer }}"

        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        if git rev-parse -q --verify "refs/tags/$TAG_NAME" >/dev/null; then
          exit 0
        fi
        git tag -a "$TAG_NAME" -m "${MSG}"
        git push origin "$TAG_NAME"

    - name: Download packages
      uses: actions/download-artifact@v4
      with:
        name: s2dumper-package-${{ needs.versioning.outputs.semVer }}
        path: ./release

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        files: |
          release/s2dumper-windows-v${{ needs.versioning.outputs.semVer }}.zip
          release/s2dumper-linux-v${{ needs.versioning.outputs.semVer }}.zip
          release/s2dumper-windows-v${{ needs.versioning.outputs.semVer }}-pdb.zip
        prerelease: ${{ needs.versioning.outputs.preReleaseLabel != '' }}
        tag_name: ${{ env.TAG_NAME }}
        name: Release v${{ needs.versioning.outputs.semVer }}
        body: ${{ needs.versioning.outputs.semVer }}
